spring:
  datasource:
    url: jdbc:h2:mem:hmrdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE # In-memory H2 database for integration tests
    driver-class-name: org.h2.Driver
    username: sa
    password:

  security:
    oauth2: #TODO

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true
#    database-platform: org.hibernate.dialect.H2Dialect

  flyway:
    enabled: false

logging:
  level:
    root: INFO
    org.hibernate.SQL: DEBUG
    org.springframework.security: DEBUG

jwt:
  secret-key: fake-secret-key-just-for-integration-tests-666
  expiration-minutes: 120